version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: tg_postgres
    restart: always
    environment:
      POSTGRES_USER: tg_admin
      POSTGRES_PASSWORD: tg_password
      POSTGRES_DB: tg_empire
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tg_network

  redis:
    image: redis:6
    container_name: tg_redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - tg_network

networks:
  tg_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
